### ISSUE TITLE
Set up federation

### ISSUE THREAD

**Issue by encadyma** [ocf/matrix#1]
Currently, the current server namespace is `matrix.ocf.berkeley.edu`, which means entities in the Matrix world are addressed by `matrix.ocf.berkeley.edu`. In the future, we should move this to `ocf.berkeley.edu`. The following has to occur:

- [x] Update `server_name` to `ocf.berkeley.edu`
- [x] Serve a file under `.well-known/matrix/server` serving according to [docs/delegate.md](https://github.com/matrix-org/synapse/blob/master/docs/delegate.md). See [this](https://github.com/ocf/puppet/blob/be68a0efe0d1c501cc386ea69682441a512b2c6c/modules/ocf_www/manifests/site/www.pp#L46-L49) for Mastodon example.

Federation tester: https://matrix.org/federationtester

**Comment by nikhiljha** [comment]
BTW: Changing `server_name` requires a database reset, so that has to be done (manually) too.

**Comment by expedited** [comment]
@nikhiljha Just checked your slack msg from yesterday, whoops. Do you know what serving the file would look like? I asked around and that was my main blocker. Sounded like it's a little more involved than the example from Mastodon

**Comment by nikhiljha** [comment]
@expedited Yeah I'm not 100% sure how that would work either. It might be easier to make an SRV record instead. I asked in IRC.

**Comment by nikhiljha** [comment]
Also, we have to update the connection endpoints in Riot. Just `:%s/matrix.ocf.berkeley.edu/ocf.berkeley.edu/g` in the riot file should work.
