### ISSUE TITLE
Add Riot client

### ISSUE THREAD

**Issue by encadyma** [ocf/matrix#11]
Replace matrix.ocf.berkeley.edu with Riot client maybe

**Comment by cg505** [comment]
If we want to do this, it should be on another domain: see vector-im/riot-web#1977. That said, just using riot.im/app seems perfectly fine.

**Comment by nikhiljha** [comment]
I think the main thing is if we host our own Riot then it can prefill the homeserver address correctly. If we tell people to use riot.im/app then they'll need to fill it in manually.

So maybe riot.ocf.berkeley.edu?

**Comment by encadyma** [comment]
Seems like a good idea, though as a note I believe riot is already the name of a staff VM, so we would have to choose something else

**Comment by ethanhs** [comment]
Perhaps https://chat.ocf.berkeley.edu ?
