### ISSUE TITLE
IRC <-> Matrix Bridge

### ISSUE THREAD

**Issue by encadyma** [ocf/matrix#4]
It's probably a safe bet to use an off-the-shelf IRC bridge like https://github.com/matrix-org/matrix-appservice-irc.

**Comment by encadyma** [comment]
Was able to get a bridge working for #matrix and #test-matrix. Once the server is more mature, bridging should also be expanded to work on more channels.

Adding a Slack <-> Matrix bridge just for the DM/group DMs might also be useful.

**Comment by cg505** [comment]
In my opinion, we should use the bridge configuration that allows arbitrary channels to be bridged without enumeration or specific approval.
